from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import zipfile

from agents.wordpress_factory_agent import WordPressBuildPlan


@dataclass(frozen=True)
class WordPressBuildResult:
    root: str
    zip_path: str
    files_created: tuple[str, ...]


class WordPressBuildExecutor:
    """Build Plan وردپرس را به اسکلت واقعی Theme/Plugin و ZIP تبدیل می‌کند."""

    def execute(self, plan: WordPressBuildPlan, output_dir: str) -> WordPressBuildResult:
        root = Path(output_dir) / plan.theme_name
        root.mkdir(parents=True, exist_ok=True)
        created: list[str] = []

        templates = {
            "style.css": f"/* Theme Name: {plan.theme_name} */\n/* Generated by AI-Agent-Manager */\n",
            "functions.php": "<?php\nif (!defined('ABSPATH')) exit;\n\nfunction ai_manager_theme_setup() { add_theme_support('title-tag'); }\nadd_action('after_setup_theme', 'ai_manager_theme_setup');\n",
            "front-page.php": "<?php get_header(); ?>\n<main id=\"primary\"><h1><?php bloginfo('name'); ?></h1><p>Generated WordPress site.</p></main>\n<?php get_footer(); ?>\n",
            "header.php": "<!doctype html><html <?php language_attributes(); ?>><head><meta charset=\"<?php bloginfo('charset'); ?>\"><?php wp_head(); ?></head><body <?php body_class(); ?>>\n",
            "footer.php": "<?php wp_footer(); ?></body></html>\n",
            "README.md": f"# {plan.project_name}\n\nTheme: `{plan.theme_name}`\n\nGenerated by AI-Agent-Manager.\n",
        }

        for artifact in plan.artifacts:
            target = Path(output_dir) / artifact.path
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.name in templates:
                content = templates[target.name]
            elif artifact.kind == "plugin":
                content = "<?php\n/** Plugin Name: AI Manager Site Leads */\nif (!defined('ABSPATH')) exit;\n"
            else:
                content = ""
            target.write_text(content, encoding="utf-8")
            created.append(str(target.relative_to(output_dir)))

        zip_path = Path(output_dir) / f"{plan.theme_name}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for path in Path(output_dir).rglob("*"):
                if path.is_file() and path != zip_path:
                    archive.write(path, path.relative_to(output_dir))

        return WordPressBuildResult(str(root), str(zip_path), tuple(created))
