"""Database specialist: schema, migrations, seeds, SQL review (SQLite default)."""

from __future__ import annotations

import re
from typing import Any

try:
    from agents.base_agent import BaseAgent
    from manager.task import Task
except Exception:  # standalone tests
    class BaseAgent:  # type: ignore
        name = "base"

        def run(self, task: Any) -> str:
            raise NotImplementedError

    class Task:  # type: ignore
        def __init__(self, **kwargs: Any) -> None:
            self.__dict__.update(kwargs)


DANGEROUS_SQL = re.compile(
    r"\b(drop\s+table|drop\s+database|truncate\s+|alter\s+table\s+\w+\s+drop)\b",
    re.I,
)


class DatabaseAgent(BaseAgent):
    name = "database"

    def run(self, task: Task) -> str:
        text = getattr(task, "description", None) or getattr(task, "goal", "") or str(task)
        lowered = text.lower()
        if "seed" in lowered:
            return self.seed_sql()
        if "index" in lowered:
            return self.suggest_indexes()
        if "migrat" in lowered:
            return self.migration_sql(text)
        if "review" in lowered or "sql" in lowered:
            return self.review_sql(text)
        return self.design_schema(text)

    def design_schema(self, spec: str) -> str:
        return (
            "-- SQLite schema draft generated by DatabaseAgent\n"
            "CREATE TABLE IF NOT EXISTS entities (\n"
            "  id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
            "  name TEXT NOT NULL,\n"
            "  payload TEXT NOT NULL DEFAULT '{}',\n"
            "  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n"
            ");\n"
            "CREATE INDEX IF NOT EXISTS idx_entities_name ON entities(name);\n"
            f"-- spec: {spec[:200]}\n"
        )

    def migration_sql(self, spec: str) -> str:
        body = (
            "-- migration: add notes column\n"
            "ALTER TABLE entities ADD COLUMN notes TEXT NOT NULL DEFAULT '';\n"
        )
        warning = ""
        if DANGEROUS_SQL.search(spec):
            warning = "WARNING: destructive SQL detected; requires HITL approval.\n"
        return warning + body

    def suggest_indexes(self) -> str:
        return "CREATE INDEX IF NOT EXISTS idx_entities_created ON entities(created_at);\n"

    def seed_sql(self) -> str:
        return "INSERT INTO entities (name, payload) VALUES ('sample', '{}');\n"

    def review_sql(self, sql: str) -> str:
        if DANGEROUS_SQL.search(sql):
            return "RISK=HIGH destructive statement found; do not auto-apply."
        return "RISK=LOW SQL appears additive."
