from __future__ import annotations

from pathlib import Path
from agents.wordpress_requirements_agent import WordPressRequirements


class WordPressThemeBuilder:
    """Requirements را به صفحات واقعی PHP داخل Theme تبدیل می‌کند."""

    def build(self, requirements: WordPressRequirements, theme_root: str) -> tuple[str, ...]:
        root = Path(theme_root)
        root.mkdir(parents=True, exist_ok=True)
        created: list[str] = []

        home_page = next((page for page in requirements.pages if page.slug == "home"), requirements.pages[0])
        sections = "".join(
            f'<section class="section-{section}"><h2>{section.replace("-", " ").title()}</h2></section>\n'
            for section in home_page.sections
        )

        header = root / "header.php"
        header.write_text(
            "<!doctype html>\n"
            "<html lang=\"fa\"><head><meta charset=\"UTF-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            "<title><?php wp_title(); ?></title><?php wp_head(); ?></head>\n"
            "<body <?php body_class(); ?>><nav aria-label=\"Primary navigation\"><a href=\"#primary\">خانه</a></nav>\n",
            encoding="utf-8",
        )
        created.append(str(header))

        footer = root / "footer.php"
        footer.write_text("<footer><p>Generated by AI-Agent-Manager</p></footer><?php wp_footer(); ?></body></html>\n", encoding="utf-8")
        created.append(str(footer))

        for page in requirements.pages:
            if page.slug == "home":
                filename = "front-page.php"
            else:
                filename = f"page-{page.slug}.php"
            page_sections = "".join(
                f'<section class="section-{section}"><h2>{section.replace("-", " ").title()}</h2></section>\n'
                for section in page.sections
            )
            content = (
                "<?php get_header(); ?>\n"
                f"<main id=\"primary\" class=\"site-page site-page-{page.slug}\">\n"
                f"<h1>{page.title}</h1>\n{page_sections}</main>\n"
                "<?php get_footer(); ?>\n"
            )
            target = root / filename
            target.write_text(content, encoding="utf-8")
            created.append(str(target))

        # Runtime محلی فایل PHP را اجرا نمی‌کند؛ یک نسخه HTML واقعی برای Browser Test می‌سازیم.
        index = root / "index.html"
        index.write_text(
            "<!doctype html>\n"
            "<html lang=\"fa\"><head><meta charset=\"UTF-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0">\n"
            f"<title>{home_page.title}</title></head><body>\n"
            "<nav aria-label=\"Primary navigation\"><a href=\"#primary\">خانه</a></nav>\n"
            f"<main id=\"primary\"><h1>{home_page.title}</h1>\n{sections}</main>\n"
            "<footer>Generated by AI-Agent-Manager</footer></body></html>\n",
            encoding="utf-8",
        )
        created.append(str(index))

        css = root / "style.css"
        css.write_text(
            "/* Theme Name: AI Manager Generated Theme */\n"
            ".site-page{max-width:1200px;margin:auto;padding:40px 20px}.section-hero{min-height:320px}.section-cta{padding:30px}\n",
            encoding="utf-8",
        )
        created.append(str(css))
        return tuple(created)
